# Generated by Django 4.2.11 on 2024-03-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_entry_slu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='slu',
            new_name='slug',
        ),
    ]
